[package]
name = "oca_conductor"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

zip_resolver = { path = "../zip_resolver" }
oca-rust = "0.1.43"
serde_json = { version = "1.0.82", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
regex = "1"
said = "0.1.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
