[package]
name = "zip_resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oca-rust = "0.1.44"
serde_json = "1.0.82"
zip = "0.6.2"
