name: npmjs.com - Transformer

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features transformer

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup yarn
        run: npm install -g yarn
      - working-directory: ./bindings/node.js
        run: yarn install
      - name: Build pkg
        working-directory: ./bindings/node.js
        run: yarn build:transformer && yarn compile:transformer
      - working-directory: ./bindings/node.js
        run: yarn test:transformer

      # - working-directory: ./bindings/node.js/pkg/transformer
      #   run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
